
###
POST http://localhost:3000/inmuebles/crear
Content-Type: application/json

{
    "piso": "2",
    "letra": "L",
    "extension": 33,
    "numero_habitaciones": 5,
    "alquilado": true,
    "propietario": "Isabella",
    "email_contacto": "isabella@isabella.com"

}


###
DELETE http://localhost:3000/inmuebles/borrar

########
### API ####
#########
GET http://localhost:3000/api/inmuebles


###
POST http://localhost:3000/api/inmuebles

###
PUT http://localhost:3000/api/inmuebles/123

###
DELETE http://localhost:3000/api/inmuebles/1234



