########
### API ####
#########

###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso": "2",
    "letra": "L",
    "extension": 33,
    "numero_habitaciones": 5,
    "alquilado": true,
    "propietario": "Isabella",
    "email_contacto": "isabella@isabella.com"

}

###
GET http://localhost:3000/api/inmuebles/

###
GET http://localhost:3000/api/inmuebles/6534346a52a491d5c1a7df3d

###
PUT http://localhost:3000/api/inmuebles/6534346a52a491d5c1a7df3d
Content-Type: application/json

{
    "piso": "6",
    "letra": "M",
    "extension": 33,
    "numero_habitaciones": 5,
    "alquilado": true,
    "propietario": "Isabella",
    "email_contacto": "isabella@isabella.com"

}

###
DELETE http://localhost:3000/api/inmuebles/6534346a52a491d5c1a7df3d